<?xml version="1.0"?>
<robot name="myrobot" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="$(find mbot_description)/urdf/c5hw_myrobot_base_gazebo.xacro" />
    <xacro:include filename="$(find mbot_description)/urdf/sensors/myrobot_laser_gazebo.xacro" />
    <xacro:include filename="$(find mbot_description)/urdf/sensors/myrobot_RGBD_gazebo.xacro" />
   

    <xacro:property name="lidar_offset_x" value="0" />
    <xacro:property name="lidar_offset_y" value="0" />
    <xacro:property name="laser_height" value="0.05" />


    <xacro:property name="RGBD_x" value="0.18"/>
    <xacro:property name="RGBD_height" value="0.04"/>


     <joint name="RGBD_joint" type="fixed">
        <origin xyz="${RGBD_x} 0 ${(base_height+RGBD_height)/2}" rpy="0 0 0" />        
        <parent link="base_link"/>
        <child link="RGBD_link" />
    </joint>
    <xacro:RGBD_camera prefix="RGBD"/>



    <!-- lidar -->
    <joint name="laser_joint" type="fixed">
        <origin xyz="${lidar_offset_x} ${lidar_offset_y} ${(laser_base_height+laser_height)/2}" rpy="0 0 0" />
        <parent link="laser_base_link"/>
        <child link="laser_link"/>
    </joint>



    <xacro:rplidar prefix="laser"/>

    
    <mbot_base_gazebo/>

</robot>
