// Generated by gencpp from file turtle_control/SpawnTurtleResponse.msg
// DO NOT EDIT!


#ifndef TURTLE_CONTROL_MESSAGE_SPAWNTURTLERESPONSE_H
#define TURTLE_CONTROL_MESSAGE_SPAWNTURTLERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace turtle_control
{
template <class ContainerAllocator>
struct SpawnTurtleResponse_
{
  typedef SpawnTurtleResponse_<ContainerAllocator> Type;

  SpawnTurtleResponse_()
    : result()  {
    }
  SpawnTurtleResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SpawnTurtleResponse_

typedef ::turtle_control::SpawnTurtleResponse_<std::allocator<void> > SpawnTurtleResponse;

typedef boost::shared_ptr< ::turtle_control::SpawnTurtleResponse > SpawnTurtleResponsePtr;
typedef boost::shared_ptr< ::turtle_control::SpawnTurtleResponse const> SpawnTurtleResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator1> & lhs, const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator1> & lhs, const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace turtle_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "turtle_control/SpawnTurtleResponse";
  }

  static const char* value(const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n"
"\n"
;
  }

  static const char* value(const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SpawnTurtleResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::turtle_control::SpawnTurtleResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::turtle_control::SpawnTurtleResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TURTLE_CONTROL_MESSAGE_SPAWNTURTLERESPONSE_H
